feat(direnv): add conda configuration for environments

diff --git a/direnv/.config/direnv/direnvrc b/direnv/.config/direnv/direnvrc
--- a/direnv/.config/direnv/direnvrc
+++ b/direnv/.config/direnv/direnvrc
@@ -13,3 +13,15 @@ layout_uv() {
     export UV_ACTIVE=1  # or VENV_ACTIVE=1
     export VIRTUAL_ENV
 }
+
+layout_anaconda() {
+  local env_name="$1"
+  if [ -f "$(conda info --base)/etc/profile.d/conda.sh" ]; then
+    source "$(conda info --base)/etc/profile.d/conda.sh"
+    conda activate "$env_name"
+  else
+    echo "Conda initialization script not found." >&2
+    exit 1
+  fi
+}
+
